// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt65Kp_jRewnjMFHlKPfYiVBfZjAa6pjw',
    appId: '1:9513561002:web:c3746a86684ccd0e6199d3',
    messagingSenderId: '9513561002',
    projectId: 'buddy-a50df',
    authDomain: 'buddy-a50df.firebaseapp.com',
    storageBucket: 'buddy-a50df.firebasestorage.app',
    measurementId: 'G-SFWY82K059',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlYOcfcb_s-RoCfKpMUELxKpNlvUnnhPs',
    appId: '1:9513561002:android:28d880ae67ae346b6199d3',
    messagingSenderId: '9513561002',
    projectId: 'buddy-a50df',
    storageBucket: 'buddy-a50df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4CropGG0w46zA5I5WhrBRP7d6lUWFw5s',
    appId: '1:9513561002:ios:c3633edd564599156199d3',
    messagingSenderId: '9513561002',
    projectId: 'buddy-a50df',
    storageBucket: 'buddy-a50df.firebasestorage.app',
    iosBundleId: 'com.example.newbuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4CropGG0w46zA5I5WhrBRP7d6lUWFw5s',
    appId: '1:9513561002:ios:c3633edd564599156199d3',
    messagingSenderId: '9513561002',
    projectId: 'buddy-a50df',
    storageBucket: 'buddy-a50df.firebasestorage.app',
    iosBundleId: 'com.example.newbuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt65Kp_jRewnjMFHlKPfYiVBfZjAa6pjw',
    appId: '1:9513561002:web:cd52cff91dc596ee6199d3',
    messagingSenderId: '9513561002',
    projectId: 'buddy-a50df',
    authDomain: 'buddy-a50df.firebaseapp.com',
    storageBucket: 'buddy-a50df.firebasestorage.app',
    measurementId: 'G-4948ZDN55R',
  );

}